name: video-trimmer # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: video-trimmer
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
    source-checksum: sha256/57be87c22d9b49c112b6d24bc67d42508660e6b718b3db89c44e47e289137082
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include
      - -usr/share
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  video-trimmer:
    after: [ rustup, ffmpeg ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/YaLTeR/video-trimmer.git
    source-tag: v0.8.1
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
      - LDFLAGS: /snap/gnome-42-2204-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:$LDFLAGS
      - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:$LD_LIBRARY_PATH
    meson-parameters:
      - --prefix=/snap/video-trimmer/current/usr
    build-packages:
      - libgstreamer-plugins-good1.0-dev
    organize:
      snap/video-trimmer/current: .
    parse-info: [ usr/share/metainfo/org.gnome.gitlab.YaLTeR.VideoTrimmer.metainfo.xml ]
    prime:
      - -snap/video-trimmer
  deps:
    after: [ video-trimmer ]
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-good
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgst1394.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstaasink.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstalaw.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstalpha.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstalphacolor.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstapetag.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstaudiofx.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstaudioparsers.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstauparse.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstautodetect.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstavi.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstcacasink.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstcairo.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstcamerabin.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstcutter.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstdebug.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstdeinterlace.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstdtmf.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstdv.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgsteffectv.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstequalizer.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstflac.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstflv.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstflxdec.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstgdkpixbuf.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstgoom.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstgoom2k1.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgsticydemux.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstid3demux.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstimagefreeze.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstinterleave.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstisomp4.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstjack.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstjpeg.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstjpegformat.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstlame.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstlevel.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmatroska.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmonoscope.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmpg123.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmulaw.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmultifile.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstmultipart.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstnavigationtest.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstoss4.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstossaudio.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstpng.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstpulseaudio.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstreplaygain.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstrtp.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstrtpmanager.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstrtsp.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstshapewipe.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstshout2.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstsmpte.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstsoup.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstspectrum.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstspeex.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgsttaglib.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgsttwolame.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstudp.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvideo4linux2.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvideobox.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvideocrop.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvideofilter.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvideomixer.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstvpx.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstwavenc.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstwavpack.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstwavparse.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgstximagesrc.so
      - usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0/libgsty4menc.so

slots:
  video-trimmer:
    interface: dbus
    bus: session
    name: org.gnome.gitlab.YaLTeR.VideoTrimmer
apps:
  video-trimmer:
    command: usr/bin/video-trimmer
    desktop: usr/share/applications/org.gnome.gitlab.YaLTeR.VideoTrimmer.desktop
    extensions: [ gnome ]
    common-id: org.gnome.gitlab.YaLTeR.VideoTrimmer
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib:/snap/gnome-platform/usr/lib:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      GTK_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0:$GTK_PATH
    plugs:
      - home
      - removable-media
