name: video-trimmer # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: video-trimmer
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  video-trimmer:
    after: [ rustup ]
    plugin: meson
    source: https://gitlab.gnome.org/YaLTeR/video-trimmer.git
    source-tag: 'v0.9.0'
    source-depth: 1
    build-environment:
      - PATH: /snap/ffmpeg-2204-sdk/current/usr/bin:$PATH
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - GI_TYPELIB_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
      - LDFLAGS: /snap/gnome-42-2204-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/girepository-1.0:/snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET
      - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    meson-parameters:
      - --prefix=/snap/video-trimmer/current/usr
    build-snaps:
      - ffmpeg-2204-sdk
    build-packages:
      - libgstreamer-plugins-good1.0-dev
    organize:
      snap/video-trimmer/current: .
    parse-info: [ usr/share/metainfo/org.gnome.gitlab.YaLTeR.VideoTrimmer.metainfo.xml ]
    prime:
      - -snap/video-trimmer
  deps:
    after: [ video-trimmer ]
    plugin: nil
    stage-packages:
      - gstreamer1.0-vaapi
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad
    override-prime: |
      craftctl default
      set -eux
      for snap in "core22" "gnome-42-2204" "ffmpeg-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done


plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204

slots:
  video-trimmer:
    interface: dbus
    bus: session
    name: org.gnome.gitlab.YaLTeR.VideoTrimmer
apps:
  video-trimmer:
    command: usr/bin/video-trimmer
    desktop: usr/share/applications/org.gnome.gitlab.YaLTeR.VideoTrimmer.desktop
    environment:
      GDK_DEBUG: portals
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH:$GI_TYPELIB_PATH:$GST_PLUGIN_PATH:$LIBGL_DRIVERS_PATH
    extensions: [ gnome ]
    common-id: org.gnome.gitlab.YaLTeR.VideoTrimmer 
    plugs:
      - home
      - removable-media
